// Banco de preguntas
const questions = {
  matematica: [
    { q: "¿Cuánto es 5 + 3?", options: ["7", "8", "9", "10"], answer: "8", difficulty: "easy" },
    { q: "Si tienes 6 manzanas y te dan 4 más, ¿cuántas manzanas tienes en total?", options: ["9", "10", "11", "12"], answer: "10", difficulty: "easy" },
    { q: "¿Cuál es el resultado de 12 + 7?", options: ["18", "19", "20", "21"], answer: "19", difficulty: "easy" },
    { q: "Suma: 25 + 10", options: ["30", "35", "40", "45"], answer: "35", difficulty: "easy" },
    { q: "¿Cuánto es 8 + 0 + 5?", options: ["12", "13", "14", "15"], answer: "13", difficulty: "easy" },
    { q: "Si un autobús lleva 15 pasajeros y suben 8 más, ¿cuántos pasajeros hay ahora?", options: ["20", "21", "22", "23"], answer: "23", difficulty: "easy" },
    { q: "¿Cuál es la suma de 30 y 15?", options: ["40", "45", "50", "55"], answer: "45", difficulty: "easy" },
    { q: "Calcula: 18 + 12", options: ["20", "25", "30", "35"], answer: "30", difficulty: "easy" },
    { q: "¿Cuánto es 7 + 7 + 7?", options: ["20", "21", "22", "23"], answer: "21", difficulty: "easy" },
    { q: "Si tienes 43 canicas y ganas 17 más, ¿cuántas canicas tienes en total?", options: ["50", "55", "60", "65"], answer: "60", difficulty: "easy" },
    { q: "¿Cuánto es 9 - 4?", options: ["4", "5", "6", "7"], answer: "5", difficulty: "easy" },
    { q: "Si tenías 10 galletas y te comiste 3, ¿cuántas galletas te quedan?", options: ["6", "7", "8", "9"], answer: "7", difficulty: "easy" },
    { q: "¿Cuál es el resultado de 15 - 6?", options: ["7", "8", "9", "10"], answer: "9", difficulty: "easy" },
    { q: "Resta: 20 - 5", options: ["10", "12", "15", "18"], answer: "15", difficulty: "easy" },
    { q: "¿Cuánto es 18 - 0 - 7?", options: ["10", "11", "12", "13"], answer: "11", difficulty: "easy" },
    { q: "Si un árbol tenía 25 hojas y se cayeron 10, ¿cuántas hojas le quedan?", options: ["10", "12", "15", "20"], answer: "15", difficulty: "easy" },
    { q: "¿Cuál es la diferencia entre 40 y 10?", options: ["20", "25", "30", "35"], answer: "30", difficulty: "easy" },
    { q: "Calcula: 33 - 13", options: ["10", "15", "20", "25"], answer: "20", difficulty: "easy" },
    { q: "¿Cuánto es 50 - 25?", options: ["15", "20", "25", "30"], answer: "25", difficulty: "easy" },
    { q: "Si tenías 60 caramelos y regalaste 20, ¿cuántos caramelos te quedan?", options: ["30", "35", "40", "45"], answer: "40", difficulty: "easy" },
    { q: "¿Cuánto es 3 x 4?", options: ["7", "10", "12", "15"], answer: "12", difficulty: "medium" },
    { q: "Si cada caja tiene 5 lápices y tienes 2 cajas, ¿cuántos lápices tienes en total?", options: ["7", "8", "10", "12"], answer: "10", difficulty: "medium" },
    { q: "¿Cuál es el resultado de 6 x 3?", options: ["12", "15", "18", "21"], answer: "18", difficulty: "medium" },
    { q: "Multiplica: 7 x 5", options: ["25", "30", "35", "40"], answer: "35", difficulty: "medium" },
    { q: "¿Cuánto es 8 x 0?", options: ["0", "8", "80", "1"], answer: "0", difficulty: "medium" },
    { q: "Si cada niño tiene 4 globos y hay 6 niños, ¿cuántos globos hay en total?", options: ["10", "18", "20", "24"], answer: "24", difficulty: "medium" },
    { q: "¿Cuál es el producto de 9 y 2?", options: ["11", "16", "18", "20"], answer: "18", difficulty: "medium" },
    { q: "Calcula: 10 x 4", options: ["14", "20", "30", "40"], answer: "40", difficulty: "medium" },
    { q: "¿Cuánto es 1 x 10?", options: ["1", "10", "11", "0"], answer: "10", difficulty: "medium" },
    { q: "Si cada paquete de galletas trae 8 galletas y compras 3 paquetes, ¿cuántas galletas tienes?", options: ["11", "16", "24", "32"], answer: "24", difficulty: "medium" },
    { q: "¿Cuánto es 10 ÷ 2?", options: ["2", "4", "5", "8"], answer: "5", difficulty: "medium" },
    { q: "Si tienes 12 caramelos y los repartes entre 3 amigos por igual, ¿cuántos caramelos le tocan a cada uno?", options: ["3", "4", "6", "9"], answer: "4", difficulty: "medium" },
    { q: "¿Cuál es el resultado de 18 ÷ 6?", options: ["2", "3", "4", "6"], answer: "3", difficulty: "medium" },
    { q: "Divide: 20 ÷ 4", options: ["4", "5", "6", "8"], answer: "5", difficulty: "medium" },
    { q: "¿Cuánto es 25 ÷ 5?", options: ["3", "4", "5", "6"], answer: "5", difficulty: "medium" },
    { q: "Si hay 24 flores y quieres hacer ramos de 4 flores cada uno, ¿cuántos ramos puedes hacer?", options: ["4", "5", "6", "8"], answer: "6", difficulty: "medium" },
    { q: "¿Cuál es el cociente de 30 y 10?", options: ["2", "3", "4", "5"], answer: "3", difficulty: "medium" },
    { q: "Calcula: 45 ÷ 9", options: ["4", "5", "6", "7"], answer: "5", difficulty: "medium" },
    { q: "¿Cuánto es 36 ÷ 6?", options: ["4", "5", "6", "7"], answer: "6", difficulty: "medium" },
    { q: "Si tienes 50 pegatinas y las pegas en 5 páginas por igual, ¿cuántas pegatinas hay en cada página?", options: ["5", "8", "10", "12"], answer: "10", difficulty: "medium" },
    { q: "María compró 3 lápices por $2 cada uno. ¿Cuánto gastó en total?", options: ["$3", "$5", "$6", "$8"], answer: "$6", difficulty: "hard" },
    { q: "Juan tenía 15 juguetes y le regaló 5 a su hermano. Luego, su mamá le compró 3 juguetes nuevos. ¿Cuántos juguetes tiene Juan ahora?", options: ["10", "13", "15", "18"], answer: "13", difficulty: "hard" },
    { q: "En un jardín hay 4 filas de árboles, y cada fila tiene 7 árboles. ¿Cuántos árboles hay en total?", options: ["11", "24", "28", "35"], answer: "28", difficulty: "hard" },
    { q: "Un pastelero hizo 24 galletas y las puso en bolsas de 6 galletas cada una. ¿Cuántas bolsas de galletas hizo?", options: ["3", "4", "5", "6"], answer: "4", difficulty: "hard" },
    { q: "Pedro tiene 10 canicas rojas y 8 canicas azules. Si pierde 4 canicas rojas, ¿cuántas canicas tiene en total ahora?", options: ["14", "18", "22", "26"], answer: "14", difficulty: "hard" },
    { q: "Un libro tiene 50 páginas. Si leí 15 páginas ayer y 10 páginas hoy, ¿cuántas páginas me faltan por leer?", options: ["20", "25", "30", "35"], answer: "25", difficulty: "hard" },
    { q: "Si un paquete de jugos trae 6 jugos y compras 4 paquetes, ¿cuántos jugos tienes?", options: ["10", "12", "18", "24"], answer: "24", difficulty: "hard" },
    { q: "Tengo 3 cajas con 5 chocolates cada una. Si me como 2 chocolates, ¿cuántos chocolates me quedan?", options: ["13", "15", "17", "18"], answer: "13", difficulty: "hard" },
    { q: "Un granjero tiene 12 gallinas y el doble de patos. ¿Cuántos patos tiene el granjero?", options: ["12", "14", "20", "24"], answer: "24", difficulty: "hard" },
    { q: "En una fiesta había 30 globos. Se reventaron 7 y se volaron 3. ¿Cuántos globos quedan?", options: ["10", "20", "23", "27"], answer: "20", difficulty: "hard" }
  ],

  comunicacion: [
    { q: "¿Qué es la comunicación?", options: ["Hablar muy alto.", "Intercambiar información, ideas o sentimientos.", "Escribir en un cuaderno.", "Jugar en silencio."], answer: "Intercambiar información, ideas o sentimientos.", difficulty: "easy" },
    { q: "¿Quién envía el mensaje en la comunicación?", options: ["El receptor.", "El canal.", "El emisor.", "El código."], answer: "El emisor.", difficulty: "easy" },
    { q: "¿Quién recibe el mensaje en la comunicación?", options: ["El emisor.", "El receptor.", "El mensaje.", "El ruido."], answer: "El receptor.", difficulty: "easy" },
    { q: "¿Qué es el mensaje?", options: ["La persona que habla.", "La información que se transmite.", "El medio por donde viaja la información.", "El idioma que se usa."], answer: "La información que se transmite.", difficulty: "easy" },
    { q: "¿Qué es el canal de comunicación?", options: ["Lo que decimos.", "La persona que escucha.", "El medio por donde viaja el mensaje (ej. aire, papel).", "El significado de las palabras."], answer: "El medio por donde viaja el mensaje (ej. aire, papel).", difficulty: "easy" },
    { q: "¿Qué es el código en la comunicación?", options: ["El lugar donde hablamos.", "El sistema de signos que usamos (ej. idioma, gestos).", "El ruido que molesta.", "La respuesta que damos."], answer: "El sistema de signos que usamos (ej. idioma, gestos).", difficulty: "easy" },
    { q: "Cuando hablas con un amigo, ¿qué tipo de comunicación estás usando?", options: ["Comunicación escrita.", "Comunicación no verbal.", "Comunicación verbal.", "Comunicación a distancia."], answer: "Comunicación verbal.", difficulty: "easy" },
    { q: "Si lees un libro, ¿qué tipo de comunicación es?", options: ["Verbal oral.", "No verbal.", "Verbal escrita.", "Gestual."], answer: "Verbal escrita.", difficulty: "easy" },
    { q: "¿Qué es un ejemplo de comunicación no verbal?", options: ["Hablar por teléfono.", "Escribir una carta.", "Hacer un gesto con la mano.", "Leer un periódico."], answer: "Hacer un gesto con la mano.", difficulty: "easy" },
    { q: "¿Qué significa escuchar activamente?", options: ["Solo oír lo que dice la otra persona.", "Prestar atención, entender y mostrar interés.", "Interrumpir para dar tu opinión.", "Pensar en otra cosa mientras el otro habla."], answer: "Prestar atención, entender y mostrar interés.", difficulty: "easy" },
    { q: "¿Por qué es importante la comunicación?", options: ["Para no tener que hablar.", "Para entender a los demás y que nos entiendan.", "Para jugar solo.", "Para hacer ruido."], answer: "Para entender a los demás y que nos entiendan.", difficulty: "easy" },
    { q: "¿Cuál de estos NO es un elemento de la comunicación?", options: ["Emisor.", "Receptor.", "Mensaje.", "El color de la ropa."], answer: "El color de la ropa.", difficulty: "easy" },
    { q: "Si tu maestra te da una instrucción, ¿quién es el emisor?", options: ["Tú.", "La maestra.", "La instrucción.", "El salón de clases."], answer: "La maestra.", difficulty: "easy" },
    { q: "Si tú respondes a tu maestra, ¿quién eres tú en ese momento?", options: ["El emisor.", "El receptor.", "El mensaje.", "El canal."], answer: "El emisor.", difficulty: "easy" },
    { q: "¿Qué es un ejemplo de canal de comunicación cuando hablas con alguien cara a cara?", options: ["El aire.", "El teléfono.", "El papel.", "La televisión."], answer: "El aire.", difficulty: "easy" },
    { q: "¿Qué código usamos cuando hablamos en español?", options: ["El código Morse.", "El idioma español.", "El lenguaje de señas.", "Los dibujos."], answer: "El idioma español.", difficulty: "easy" },
    { q: "¿Qué es el feedback o retroalimentación en la comunicación?", options: ["El inicio de la conversación.", "La respuesta del receptor al emisor.", "El ruido que interrumpe.", "El tema de la conversación."], answer: "La respuesta del receptor al emisor.", difficulty: "easy" },
    { q: "Si alguien te sonríe, ¿qué te está comunicando?", options: ["Que está enojado.", "Que está triste.", "Que está contento o es amigable.", "Que tiene frío."], answer: "Que está contento o es amigable.", difficulty: "easy" },
    { q: "¿Qué es una barrera de comunicación?", options: ["Algo que ayuda a que el mensaje llegue claro.", "Algo que dificulta que el mensaje se entienda.", "Un tipo de mensaje.", "Una forma de hablar."], answer: "Algo que dificulta que el mensaje se entienda.", difficulty: "easy" },
    { q: "Un ejemplo de barrera de comunicación es:", options: ["Hablar claro.", "Escuchar con atención.", "Mucho ruido en el ambiente.", "Usar el mismo idioma."], answer: "Mucho ruido en el ambiente.", difficulty: "easy" },
    { q: "¿Qué es la comunicación asertiva?", options: ["Hablar sin pensar.", "Expresar tus ideas y sentimientos respetando a los demás.", "Gritar para que te escuchen.", "No decir lo que piensas."], answer: "Expresar tus ideas y sentimientos respetando a los demás.", difficulty: "medium" },
    { q: "¿Por qué es importante ser claro al hablar?", options: ["Para que nadie te entienda.", "Para que el mensaje sea confuso.", "Para que el receptor entienda bien el mensaje.", "Para hablar más rápido."], answer: "Para que el receptor entienda bien el mensaje.", difficulty: "medium" },
    { q: "Si ves una señal de \"STOP\" en la calle, ¿qué tipo de comunicación es?", options: ["Verbal.", "No verbal (visual).", "Auditiva.", "Táctil."], answer: "No verbal (visual).", difficulty: "medium" },
    { q: "¿Qué es un sinónimo de \"hablar\"?", options: ["Callar.", "Comunicar.", "Esconder.", "Ignorar."], answer: "Comunicar.", difficulty: "medium" },
    { q: "¿Qué es un antónimo de \"escuchar\"?", options: ["Oír.", "Atender.", "Ignorar.", "Comprender."], answer: "Ignorar.", difficulty: "medium" },
    { q: "Cuando escribes un mensaje de texto, ¿cuál es el canal?", options: ["Tu voz.", "El teléfono móvil.", "El papel.", "Tus gestos."], answer: "El teléfono móvil.", difficulty: "medium" },
    { q: "¿Qué es un gesto?", options: ["Una palabra.", "Un movimiento del cuerpo para comunicar algo.", "Un sonido.", "Un dibujo."], answer: "Un movimiento del cuerpo para comunicar algo.", difficulty: "medium" },
    { q: "¿Por qué es importante mirar a los ojos cuando hablas con alguien?", options: ["Para asustarlo.", "Para mostrar que estás prestando atención y eres sincero.", "Para ver qué color de ojos tiene.", "Para no escuchar."], answer: "Para mostrar que estás prestando atención y eres sincero.", difficulty: "medium" },
    { q: "Si alguien te cuenta un secreto, ¿qué debes hacer?", options: ["Contárselo a todos.", "Guardar el secreto y respetar su confianza.", "Reírte de él.", "Olvidarlo inmediatamente."], answer: "Guardar el secreto y respetar su confianza.", difficulty: "medium" },
    { q: "¿Qué es la empatía en la comunicación?", options: ["Sentir lo mismo que la otra persona.", "Ponerte en el lugar del otro para entender sus sentimientos.", "No preocuparte por los demás.", "Solo hablar de ti mismo."], answer: "Ponerte en el lugar del otro para entender sus sentimientos.", difficulty: "medium" },
    { q: "¿Cuál de estas es una buena forma de comunicarse en el aula?", options: ["Gritar para pedir la palabra.", "Levantar la mano para hablar.", "Hablar con tu compañero mientras la maestra explica.", "No decir nada nunca."], answer: "Levantar la mano para hablar.", difficulty: "medium" },
    { q: "Si no entiendes algo que te dicen, ¿qué es lo mejor que puedes hacer?", options: ["Fingir que entendiste.", "Preguntar para que te lo expliquen de nuevo.", "Quedarte callado y no hacer nada.", "Enojarse."], answer: "Preguntar para que te lo expliquen de nuevo.", difficulty: "medium" },
    { q: "¿Qué es la comunicación escrita?", options: ["Hablar por teléfono.", "Usar gestos.", "Escribir cartas, correos o mensajes.", "Escuchar música."], answer: "Escribir cartas, correos o mensajes.", difficulty: "medium" },
    { q: "¿Qué es la comunicación oral?", options: ["Leer un libro.", "Hablar y escuchar.", "Dibujar.", "Escribir en un cuaderno."], answer: "Hablar y escuchar.", difficulty: "medium" },
    { q: "Cuando un semáforo cambia de color, ¿qué nos está comunicando?", options: ["Que hay un coche.", "Que podemos pasar o debemos detenernos.", "Que va a llover.", "Que es de noche."], answer: "Que podemos pasar o debemos detenernos.", difficulty: "medium" },
    { q: "¿Qué es un diálogo?", options: ["Una persona hablando sola.", "Dos o más personas conversando.", "Un libro.", "Un dibujo."], answer: "Dos o más personas conversando.", difficulty: "medium" },
    { q: "¿Por qué es importante esperar tu turno para hablar?", options: ["Para que la conversación sea desordenada.", "Para que todos puedan expresarse y la conversación sea respetuosa.", "Para que nadie te escuche.", "Para que te aburras."], answer: "Para que todos puedan expresarse y la conversación sea respetuosa.", difficulty: "medium" },
    { q: "Si ves a alguien con los brazos cruzados y el ceño fruncido, ¿qué podría estar comunicando?", options: ["Que está muy feliz.", "Que está enojado o molesto.", "Que tiene frío.", "Que está bailando."], answer: "Que está enojado o molesto.", difficulty: "medium" },
    { q: "¿Qué es un rumor?", options: ["Una noticia verdadera y confirmada.", "Una información que se difunde sin saber si es cierta.", "Un cuento.", "Una canción."], answer: "Una información que se difunde sin saber si es cierta.", difficulty: "medium" },
    { q: "¿Por qué no debemos difundir rumores?", options: ["Porque son divertidos.", "Porque pueden dañar a las personas y causar problemas.", "Porque son secretos.", "Porque nadie los cree."], answer: "Porque pueden dañar a las personas y causar problemas.", difficulty: "medium" },
    { q: "¿Qué es un buen comunicador?", options: ["Alguien que solo habla de sí mismo.", "Alguien que sabe escuchar y expresarse claramente.", "Alguien que nunca dice lo que piensa.", "Alguien que siempre interrumpe."], answer: "Alguien que sabe escuchar y expresarse claramente.", difficulty: "hard" },
    { q: "¿Qué significa \"lenguaje corporal\"?", options: ["El idioma que hablamos.", "La forma en que nuestro cuerpo comunica sin palabras.", "Los sonidos que hacemos.", "Las letras que escribimos."], answer: "La forma en que nuestro cuerpo comunica sin palabras.", difficulty: "hard" },
    { q: "Si tu amigo te pide ayuda, ¿qué es una buena respuesta?", options: ["Ignorarlo.", "Decirle que no puedes sin explicar por qué.", "Preguntarle cómo puedes ayudarlo.", "Reírte de él."], answer: "Preguntarle cómo puedes ayudarlo.", difficulty: "hard" },
    { q: "¿Qué es un pictograma?", options: ["Una palabra escrita.", "Un dibujo que representa una idea o un objeto.", "Un sonido.", "Un número."], answer: "Un dibujo que representa una idea o un objeto.", difficulty: "hard" },
    { q: "¿Cuál de estas es una forma de comunicación a distancia?", options: ["Hablar con tu mamá en casa.", "Escribir una carta a un amigo que vive lejos.", "Jugar con tus compañeros en el recreo.", "Hablar con tu maestra en el salón."], answer: "Escribir una carta a un amigo que vive lejos.", difficulty: "hard" },
    { q: "¿Qué es la expresión facial?", options: ["La forma en que movemos las manos.", "Los gestos que hacemos con la cara para comunicar emociones.", "La forma en que caminamos.", "El tono de voz."], answer: "Los gestos que hacemos con la cara para comunicar emociones.", difficulty: "hard" },
    { q: "Si alguien te está hablando, ¿qué postura corporal muestra que estás atento?", options: ["Mirar al suelo.", "Estar de espaldas.", "Mirar a la persona y tener una postura abierta.", "Estar jugando con algo."], answer: "Mirar a la persona y tener una postura abierta.", difficulty: "hard" },
    { q: "¿Qué es un malentendido?", options: ["Cuando dos personas se entienden perfectamente.", "Cuando el mensaje no se interpreta correctamente.", "Cuando se habla muy claro.", "Cuando se usa el mismo idioma."], answer: "Cuando el mensaje no se interpreta correctamente.", difficulty: "hard" },
    { q: "¿Cómo podemos evitar los malentendidos?", options: ["Hablando muy rápido.", "Preguntando si hemos entendido bien y pidiendo aclaraciones.", "No prestando atención.", "Usando palabras difíciles."], answer: "Preguntando si hemos entendido bien y pidiendo aclaraciones.", difficulty: "hard" },
    { q: "¿Qué es lo más importante para una buena comunicación?", options: ["Hablar mucho.", "Escuchar y entender al otro, y expresarse con respeto y claridad.", "Solo dar órdenes.", "No decir lo que sientes."], answer: "Escuchar y entender al otro, y expresarse con respeto y claridad.", difficulty: "hard" }
  ],
  historia: [
    { q: "En el Imperio Inca, se le conocía como el dios creador del mundo, del cielo y las estrellas:", options: ["Quetzalcóatl", "Ixchel", "Viracocha"], answer: "Viracocha", difficulty: "easy" },
    { q: "¿Cuándo se fundó la ciudad de Lima?", options: ["El 6 de agosto de 1538", "El 18 de enero de 1535", "El 20 de diciembre de 1592"], answer: "El 18 de enero de 1535", difficulty: "easy" },
    { q: "¿Contra qué país se enfrentó Perú en la Guerra del Pacífico entre 1879 y 1884?", options: ["Argentina", "Colombia", "Chile"], answer: "Chile", difficulty: "easy" },
    { q: "¿En qué fecha se proclamó la Independencia del Perú?", options: ["18 de julio de 1821", "28 de julio de 1821", "9 de diciembre de 1824"], answer: "28 de julio de 1821", difficulty: "easy" },
    { q: "¿Quiénes fueron los Incas?", options: ["Una civilización precolombina", "Los conquistadores españoles", "Los primeros habitantes de Lima"], answer: "Una civilización precolombina", difficulty: "easy" },
    { q: "¿Qué sitio arqueológico es considerado una de las siete maravillas del mundo moderno en Perú?", options: ["Líneas de Nazca", "Chan Chan", "Machu Picchu"], answer: "Machu Picchu", difficulty: "easy" },
    { q: "¿En qué región geográfica del país se encuentra Machu Picchu?", options: ["Lima", "Cusco", "Arequipa"], answer: "Cusco", difficulty: "easy" },
    { q: "¿Qué acontecimiento marca el inicio de la prehistoria?", options: ["La invención de la escritura", "El origen del hombre", "El desarrollo de la agricultura"], answer: "El origen del hombre", difficulty: "easy" },
    { q: "¿A quién se le considera como el “Padre de la Arqueología Peruana”?", options: ["Julio C. Tello", "Max Uhle", "Federico Kauffmann Doig"], answer: "Julio C. Tello", difficulty: "easy" },
    { q: "¿En qué continente aparece el primer hombre?", options: ["América", "Asia", "África"], answer: "África", difficulty: "easy" },
    { q: "¿A qué cultura del antiguo Perú le pertenecen las trepanaciones craneanas?", options: ["Cultura Nazca", "Cultura Paracas", "Cultura Mochica"], answer: "Cultura Paracas", difficulty: "easy" },
    { q: "¿Cuál fue la capital del Imperio Inca?", options: ["Lima", "Chan Chan", "Cusco"], answer: "Cusco", difficulty: "easy" },
    { q: "¿Quién fue el conquistador español que lideró la expedición al Perú?", options: ["Hernán Cortés", "Francisco Pizarro", "Diego de Almagro"], answer: "Francisco Pizarro", difficulty: "easy" },
    { q: "¿Cómo se llamó el último inca del Tahuantinsuyo?", options: ["Pachacútec", "Túpac Amaru I", "Atahualpa"], answer: "Atahualpa", difficulty: "easy" },
    { q: "¿Quién proclamó la Independencia del Perú?", options: ["Simón Bolívar", "José de San Martín", "Túpac Amaru II"], answer: "José de San Martín", difficulty: "easy" },
    { q: "¿Cuál es el nombre del héroe naval peruano conocido como \"El Caballero de los Mares\"?", options: ["Francisco Bolognesi", "Miguel Grau", "Alfonso Ugarte"], answer: "Miguel Grau", difficulty: "easy" },
    { q: "¿En qué batalla se selló la independencia definitiva del Perú?", options: ["Batalla de Junín", "Batalla de Ayacucho", "Batalla de Miraflores"], answer: "Batalla de Ayacucho", difficulty: "easy" },
    { q: "¿Cuál fue la primera cultura preincaica en el Perú?", options: ["Chavín", "Nazca", "Mochica"], answer: "Chavín", difficulty: "easy" },
    { q: "¿Qué cultura preincaica es famosa por sus geoglifos en el desierto?", options: ["Cultura Moche", "Cultura Nazca", "Cultura Chimú"], answer: "Cultura Nazca", difficulty: "easy" },
    { q: "¿Qué animal es un símbolo nacional del Perú y se encuentra en su escudo?", options: ["Llama", "Alpaca", "Vicuña"], answer: "Vicuña", difficulty: "easy" },
    { q: "¿Cuál es el nombre del lago navegable más alto del mundo, compartido por Perú y Bolivia?", options: ["Lago Titicaca", "Lago Poopó", "Lago Junín"], answer: "Lago Titicaca", difficulty: "medium" },
    { q: "¿Cuál fue la capital del Virreinato del Perú?", options: ["Cusco", "Trujillo", "Lima"], answer: "Lima", difficulty: "medium" },
    { q: "¿Quién fue el líder de la rebelión de Túpac Amaru II?", options: ["José Gabriel Condorcanqui", "Manco Inca", "Sayri Túpac"], answer: "José Gabriel Condorcanqui", difficulty: "medium" },
    { q: "¿Qué civilización construyó la ciudad de Chan Chan, la ciudad de barro más grande de América?", options: ["Inca", "Chimú", "Wari"], answer: "Chimú", difficulty: "medium" },
    { q: "¿Cuál es el nombre del dios inca del sol?", options: ["Viracocha", "Pachacámac", "Inti"], answer: "Inti", difficulty: "medium" },
    { q: "¿Qué nombre recibían los caminos construidos por los incas?", options: ["Qhapaq Ñan", "Caminos Reales", "Vías Incas"], answer: "Qhapaq Ñan", difficulty: "medium" },
    { q: "¿Qué instrumento musical de viento es originario del Perú y se usa en la música andina?", options: ["Guitarra", "Zampoña", "Cajón"], answer: "Zampoña", difficulty: "medium" },
    { q: "¿Cuál es el plato bandera del Perú?", options: ["Lomo Saltado", "Ají de Gallina", "Ceviche"], answer: "Ceviche", difficulty: "medium" },
    { q: "¿Qué baile típico peruano es conocido por el uso de pañuelos?", options: ["Huayno", "Marinera", "Festejo"], answer: "Marinera", difficulty: "medium" },
    { q: "¿Quién fue el primer presidente del Perú?", options: ["Simón Bolívar", "José de la Riva-Agüero", "Ramón Castilla"], answer: "José de la Riva-Agüero", difficulty: "medium" },
    { q: "¿En qué año se fundó la Universidad Nacional Mayor de San Marcos, la más antigua de América?", options: ["1535", "1551", "1600"], answer: "1551", difficulty: "medium" },
    { q: "¿Qué cultura preincaica es conocida por sus huacos retratos?", options: ["Nazca", "Mochica", "Paracas"], answer: "Mochica", difficulty: "medium" },
    { q: "¿Qué nombre se le da al período de la historia del Perú antes de la llegada de los españoles?", options: ["Virreinato", "República", "Preincaico"], answer: "Preincaico", difficulty: "medium" },
    { q: "¿Cuál fue el principal cultivo de los incas?", options: ["Trigo", "Arroz", "Papa"], answer: "Papa", difficulty: "medium" },
    { q: "¿Qué sistema de registro utilizaban los incas, basado en nudos?", options: ["Escritura jeroglífica", "Quipu", "Tablillas de arcilla"], answer: "Quipu", difficulty: "medium" },
    { q: "¿Qué ciudad fue el centro del Imperio Wari?", options: ["Pikillaqta", "Wari", "Cajamarca"], answer: "Wari", difficulty: "medium" },
    { q: "¿Qué personaje histórico es conocido como \"El Brujo de los Andes\" por su resistencia en la Guerra del Pacífico?", options: ["Miguel Grau", "Francisco Bolognesi", "Andrés Avelino Cáceres"], answer: "Andrés Avelino Cáceres", difficulty: "medium" },
    { q: "¿Qué batalla fue la última gran confrontación terrestre de las guerras de independencia hispanoamericanas?", options: ["Batalla de Junín", "Batalla de Ayacucho", "Batalla de Tarapacá"], answer: "Batalla de Ayacucho", difficulty: "medium" },
    { q: "¿Qué virrey del Perú es recordado por sus reformas y organización del virreinato?", options: ["Francisco de Toledo", "Blasco Núñez Vela", "Antonio de Mendoza"], answer: "Francisco de Toledo", difficulty: "medium" },
    { q: "¿Qué animal andino es valorado por su fina lana?", options: ["Llama", "Alpaca", "Guanaco"], answer: "Alpaca", difficulty: "medium" },
    { q: "¿Qué cultura preincaica construyó la fortaleza de Kuélap?", options: ["Moche", "Chimú", "Chachapoyas"], answer: "Chachapoyas", difficulty: "hard" },
    { q: "¿Qué nombre se le dio al territorio del Imperio Inca?", options: ["Mayab", "Tahuantinsuyo", "Anáhuac"], answer: "Tahuantinsuyo", difficulty: "hard" },
    { q: "¿Quién fue el primer virrey del Perú?", options: ["Francisco de Toledo", "Blasco Núñez Vela", "Antonio de Mendoza"], answer: "Blasco Núñez Vela", difficulty: "hard" },
    { q: "¿Qué importante documento firmó el Perú con Chile después de la Guerra del Pacífico?", options: ["Tratado de Ancón", "Tratado de Paz y Amistad", "Tratado de Límites"], answer: "Tratado de Ancón", difficulty: "hard" },
    { q: "¿Qué cultura preincaica es famosa por sus textiles y mantos funerarios?", options: ["Nazca", "Paracas", "Wari"], answer: "Paracas", difficulty: "hard" },
    { q: "¿Qué ciudad fue la capital del Imperio Chimú?", options: ["Túcume", "Chan Chan", "Sipán"], answer: "Chan Chan", difficulty: "hard" },
    { q: "¿Qué nombre recibían los mensajeros del Imperio Inca que corrían por los caminos?", options: ["Chasquis", "Tambos", "Curacas"], answer: "Chasquis", difficulty: "hard" },
    { q: "¿Qué mineral fue muy importante para la economía del Virreinato del Perú?", options: ["Cobre", "Oro", "Plata"], answer: "Plata", difficulty: "hard" },
    { q: "¿Qué batalla naval se libró durante la Guerra del Pacífico, donde Miguel Grau se inmoló?", options: ["Combate de Abtao", "Combate de Iquique", "Combate de Angamos"], answer: "Combate de Angamos", difficulty: "hard" },
    { q: "¿Qué nombre se le da al período de la historia del Perú después de la Independencia?", options: ["Virreinato", "República", "Colonia"], answer: "República", difficulty: "hard" }
  ],

  ciencia: [
    { q: "¿Qué tres partes principales tiene el cuerpo humano?", options: ["Cabeza, piernas y brazos", "Cuerpo, piernas y brazos", "Cabeza, tronco y extremidades", "Ojos, nariz y boca"], answer: "Cabeza, tronco y extremidades", difficulty: "easy" },
    { q: "¿Cuál es el órgano más grande del cuerpo humano?", options: ["Corazón", "Pulmones", "Intestinos", "Piel"], answer: "Piel", difficulty: "easy" },
    { q: "¿Para qué sirven los sentidos?", options: ["Para sobrevivir", "Para relacionarnos con el mundo que nos rodea", "Para mejorar el rendimiento del cuerpo humano", "Para dormir"], answer: "Para relacionarnos con el mundo que nos rodea", difficulty: "easy" },
    { q: "¿Cómo se llama la parte del cuerpo donde se juntan dos o más huesos?", options: ["Cartílagos", "Tendones", "Articulaciones", "Músculos"], answer: "Articulaciones", difficulty: "easy" },
    { q: "¿Cuántos huesos tiene aproximadamente un adulto?", options: ["100", "206", "300", "50"], answer: "206", difficulty: "easy" },
    { q: "¿Qué órgano bombea la sangre a todo el cuerpo?", options: ["Pulmones", "Cerebro", "Corazón", "Estómago"], answer: "Corazón", difficulty: "easy" },
    { q: "¿Qué gas necesitamos para respirar?", options: ["Dióxido de carbono", "Nitrógeno", "Oxígeno", "Hidrógeno"], answer: "Oxígeno", difficulty: "easy" },
    { q: "¿Dónde se encuentran las papilas gustativas que nos permiten saborear los alimentos?", options: ["En la nariz", "En los ojos", "En la lengua", "En los oídos"], answer: "En la lengua", difficulty: "easy" },
    { q: "¿Cuál es el hueso más duro del cuerpo humano?", options: ["Fémur", "Cráneo", "Mandíbula", "Tibia"], answer: "Fémur", difficulty: "easy" },
    { q: "¿Qué parte del cuerpo nos permite pensar y controlar nuestras acciones?", options: ["Corazón", "Estómago", "Cerebro", "Hígado"], answer: "Cerebro", difficulty: "easy" },
    { q: "¿Cómo se clasifican los animales según tengan columna vertebral o no?", options: ["Animales ovíparos o vivíparos", "Animales vertebrados y animales invertebrados", "Animales carnívoros, herbívoros u omnívoros", "Animales salvajes o domésticos"], answer: "Animales vertebrados y animales invertebrados", difficulty: "easy" },
    { q: "¿Qué tipo de animal es el zorro?", options: ["Felino", "Canino", "Equino", "Roedor"], answer: "Canino", difficulty: "easy" },
    { q: "¿Cuál es el animal terrestre más alto del mundo?", options: ["Elefante", "Oso", "Jirafa", "Rinoceronte"], answer: "Jirafa", difficulty: "easy" },
    { q: "¿Qué animal mamífero puede volar?", options: ["Albatros", "Murciélago", "Saltamontes", "Águila"], answer: "Murciélago", difficulty: "easy" },
    { q: "¿Qué utilizan los peces para respirar?", options: ["Pulmones", "Piel", "Branquias", "Nariz"], answer: "Branquias", difficulty: "easy" },
    { q: "¿Cuántas patas tiene una araña?", options: ["Seis", "Ocho", "Cuatro", "Diez"], answer: "Ocho", difficulty: "easy" },
    { q: "¿Cuál es el animal conocido como \"el mejor amigo del hombre\"?", options: ["Gato", "Caballo", "Perro", "Pájaro"], answer: "Perro", difficulty: "easy" },
    { q: "¿Qué animal es famoso por su caparazón y por ser muy lento?", options: ["Conejo", "Tortuga", "Serpiente", "Tigre"], answer: "Tortuga", difficulty: "easy" },
    { q: "¿Qué animal pone huevos y tiene plumas?", options: ["Perro", "Vaca", "Gallina", "Pez"], answer: "Gallina", difficulty: "easy" },
    { q: "¿Cuál de estos animales no es un mamífero?", options: ["Ballena", "Emú", "Canguro", "Delfín"], answer: "Emú", difficulty: "easy" },
    { q: "¿Para qué sirve la raíz de las plantas?", options: ["Para hacer fotosíntesis", "Para absorber agua y nutrientes", "Para atraer insectos", "Para producir flores"], answer: "Para absorber agua y nutrientes", difficulty: "medium" },
    { q: "¿Cómo se llama el proceso mediante el cual las plantas producen su propio alimento?", options: ["Respiración", "Transpiración", "Fotosíntesis", "Germinación"], answer: "Fotosíntesis", difficulty: "medium" },
    { q: "¿Cómo nacen los árboles?", options: ["A partir de óvulos", "A partir de espermas", "A partir de una semilla", "A partir de una hoja"], answer: "A partir de una semilla", difficulty: "medium" },
    { q: "¿Qué absorbe la planta a través de sus hojas?", options: ["Agua", "Dióxido de carbono", "Nutrientes del suelo", "Luz solar"], answer: "Dióxido de carbono", difficulty: "medium" },
    { q: "¿Qué parte de la planta se convierte en fruto?", options: ["La raíz", "El tallo", "La flor", "La hoja"], answer: "La flor", difficulty: "medium" },
    { q: "¿Qué necesitan las plantas para crecer?", options: ["Agua, luz solar y aire", "Carne, leche y pan", "Rocas, arena y viento", "Nieve, hielo y frío"], answer: "Agua, luz solar y aire", difficulty: "medium" },
    { q: "¿Qué producen las plantas que es esencial para la vida en la Tierra?", options: ["Dióxido de carbono", "Agua", "Oxígeno", "Nitrógeno"], answer: "Oxígeno", difficulty: "medium" },
    { q: "¿Cuál de estas no es una parte principal de una planta?", options: ["Raíz", "Tallo", "Rueda", "Hoja"], answer: "Rueda", difficulty: "medium" },
    { q: "¿Qué tipo de planta tiene un tronco leñoso y ramas?", options: ["Hierba", "Arbusto", "Árbol", "Hongo"], answer: "Árbol", difficulty: "medium" },
    { q: "¿Qué es la clorofila?", options: ["Un tipo de flor", "El pigmento verde de las plantas", "Un nutriente del suelo", "Un tipo de insecto"], answer: "El pigmento verde de las plantas", difficulty: "medium" },
    { q: "¿Cuál es el planeta más grande de nuestro sistema solar?", options: ["Urano", "Neptuno", "Marte", "Júpiter"], answer: "Júpiter", difficulty: "medium" },
    { q: "¿Cuál es el planeta más cercano al Sol?", options: ["Tierra", "Marte", "Venus", "Mercurio"], answer: "Mercurio", difficulty: "medium" },
    { q: "¿Cuál es la estrella más cercana al planeta Tierra?", options: ["La Luna", "Marte", "El Sol", "Venus"], answer: "El Sol", difficulty: "medium" },
    { q: "¿Cuál es el satélite natural de la Tierra?", options: ["Marte", "El Sol", "La Luna", "Venus"], answer: "La Luna", difficulty: "medium" },
    { q: "¿En qué galaxia se encuentra el sistema solar?", options: ["Andrómeda", "Triángulo", "Vía Láctea", "Remolino"], answer: "Vía Láctea", difficulty: "medium" },
    { q: "¿Qué planeta es conocido como el \"planeta rojo\"?", options: ["Venus", "Marte", "Júpiter", "Saturno"], answer: "Marte", difficulty: "medium" },
    { q: "¿Cuántos planetas hay en nuestro sistema solar?", options: ["7", "8", "9", "10"], answer: "8", difficulty: "medium" },
    { q: "¿Qué cuerpo celeste está formado principalmente por hielo y polvo y tiene una cola brillante?", options: ["Asteroide", "Cometa", "Meteorito", "Planeta"], answer: "Cometa", difficulty: "medium" },
    { q: "¿Qué es una galaxia?", options: ["Un planeta muy grande", "Un conjunto de estrellas, gas y polvo", "Un tipo de estrella", "Un agujero negro"], answer: "Un conjunto de estrellas, gas y polvo", difficulty: "medium" },
    { q: "¿Qué instrumento usamos para ver objetos lejanos en el espacio?", options: ["Microscopio", "Telescopio", "Binoculares", "Lupa"], answer: "Telescopio", difficulty: "medium" },
    { q: "¿Qué es la materia?", options: ["Es la energía que captamos del sol", "Es todo lo que existe y tiene masa y volumen", "Es una sustancia del cual están hechos los objetos", "Es el espacio vacío"], answer: "Es todo lo que existe y tiene masa y volumen", difficulty: "hard" },
    { q: "¿A qué temperatura hierve el agua?", options: ["0 grados Celsius", "50 grados Celsius", "100 grados Celsius", "200 grados Celsius"], answer: "100 grados Celsius", difficulty: "hard" },
    { q: "¿Qué tipo de cargas eléctricas existen?", options: ["Carga rápida y carga lenta", "Carga vertical y carga horizontal", "Carga positiva y carga negativa", "Carga grande y carga pequeña"], answer: "Carga positiva y carga negativa", difficulty: "hard" },
    { q: "¿Qué es la nieve?", options: ["Agua líquida", "Agua congelada", "Vapor de agua", "Hielo seco"], answer: "Agua congelada", difficulty: "hard" },
    { q: "¿Qué une tus músculos a los huesos?", options: ["Cartílagos", "Ligamentos", "Tendones", "Articulaciones"], answer: "Tendones", difficulty: "hard" },
    { q: "¿Cuál es la velocidad aproximada a la que viaja la luz?", options: ["30,000 km/h", "300,000 km por segundo", "300,000 m/segundo", "3 millones de m/segundo"], answer: "300,000 km por segundo", difficulty: "hard" },
    { q: "¿Qué es un imán?", options: ["Un objeto que produce luz", "Un objeto que atrae metales", "Un objeto que flota en el agua", "Un objeto que produce calor"], answer: "Un objeto que atrae metales", difficulty: "hard" },
    { q: "¿Qué es la energía?", options: ["La capacidad de hacer un trabajo", "Un tipo de materia", "Un gas invisible", "Un líquido"], answer: "La capacidad de hacer un trabajo", difficulty: "hard" },
    { q: "¿Qué es un volcán?", options: ["Una montaña muy alta", "Una abertura en la Tierra por donde sale magma", "Un tipo de nube", "Un lago de agua caliente"], answer: "Una abertura en la Tierra por donde sale magma", difficulty: "hard" },
    { q: "¿Qué es el sonido?", options: ["Una forma de luz", "Una vibración que viaja por el aire o el agua", "Un tipo de energía eléctrica", "Un gas"], answer: "Una vibración que viaja por el aire o el agua", difficulty: "hard" }
  ]
};
